/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: "#864200",
        "on-surface-variant": "#3f4940",
        "surface-dim": "#d8dadd",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffece2",
        "tertiary-fixed-dim": "#ffb785",
        "primary-fixed": "#9cf6b6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e2e5",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3133",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#00210e",
        secondary: "#0058bb",
        "surface-container": "#eceef0",
        "on-secondary-fixed": "#001a41",
        "on-primary-fixed-variant": "#00522b",
        "inverse-primary": "#80d99c",
        primary: "#006234",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#adc7ff",
        "tertiary-container": "#ab5600",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#80d99c",
        "on-tertiary-fixed": "#301400",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#d8e2ff",
        outline: "#6f7a70",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-container": "#bcffcc",
        "on-tertiary-fixed-variant": "#713700",
        "surface-container-high": "#e7e8eb",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e1e2e5",
        "on-secondary-container": "#fefcff",
        "outline-variant": "#bec9be",
        background: "#f8f9fc",
        "primary-container": "#1e7c48",
        surface: "#f8f9fc",
        "on-tertiary": "#ffffff",
        "secondary-container": "#1471e6",
        "surface-tint": "#016d3b",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#004493",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        gutter: "1.25rem",
        margin: "2rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2.25rem",
      },
      fontFamily: {
        "label-lg": ["JetBrains Mono"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["JetBrains Mono"],
        "body-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};